#!/usr/bin/env python3
"""Write the RESOLVED VALUES of every matrix into its own doc, from the columns.

Why this exists: each `docs/<NAME>-MATRIX.md` was written as prose and hand-made
tables describing what the three systems do, while the authoritative values live
in `columns/<name>.{salt,shadcn,m3}.json`. Two copies of the same fact
drift — and the prose copy is the one people read.

So the doc stops asserting values in its own words. This regenerates a delimited
block at the end of each matrix doc containing every row × every system, read
straight from the column files, with each cell's own citation. Re-runnable: the
block between the markers is replaced, everything a human wrote above it is left
alone.

Run it after ANY column edit:  python3 scripts/sync-matrix-values.py
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TPL = os.path.join(ROOT, "contract", "templates")
COLS = os.path.join(ROOT, "columns")
DOCS = os.path.join(ROOT, "matrices")
SYSTEMS = ["salt", "shadcn", "m3"]

BEGIN = "<!-- BEGIN GENERATED VALUES — written by scripts/sync-matrix-values.py, do not hand-edit -->"
END = "<!-- END GENERATED VALUES -->"


def esc(t):
    return str(t).replace("|", "\\|").replace("\n", " ").strip()


def render_cell(cell):
    """One system's answer, compressed to a table cell."""
    if cell is None:
        return "—", ""
    kind = cell.get("kind")
    cite = cell.get("source") or cell.get("note") or ""
    if kind == "off":
        return "**off**", cite
    if kind == "alias":
        return "⟡ `%s`" % cell.get("slot", "?"), cite
    if kind == "inherit":
        return "_inherit_", cite
    v = cell.get("value")
    if isinstance(v, dict):
        v = "; ".join("%s: %s" % (k, x) for k, x in v.items())
    elif isinstance(v, list):
        v = ", ".join(map(str, v))
    if kind == "expression":
        return "ƒ `%s`" % esc(v), cite
    if kind == "native":
        return "`%s`" % esc(cell.get("token") or v), cite
    return "`%s`" % esc(v), cite


def block_for(comp):
    tpl = json.load(open(os.path.join(TPL, comp + ".template.json"), encoding="utf-8"))
    cols = {}
    for s in SYSTEMS:
        p = os.path.join(COLS, "%s.%s.json" % (comp, s))
        cols[s] = json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None

    out = [BEGIN, "",
           "## Resolved values — generated from the columns",
           "",
           "*Every row of `contract/templates/%s.template.json` against every system, read "
           "from `columns/%s.*.json`. This block is regenerated by "
           "`scripts/sync-matrix-values.py`; the prose above is hand-written. If the two ever "
           "disagree, this block is the data and the prose is the claim.*" % (comp, comp),
           ""]

    # slots first — the raw values the cells alias into
    out += ["### Slots", ""]
    any_slot = False
    for s in SYSTEMS:
        col = cols[s]
        if not col:
            continue
        light = (col.get("slots") or {}).get("light") or {}
        dark = (col.get("slots") or {}).get("dark") or {}
        dens = (col.get("slots") or {}).get("byDensity") or {}
        if not light and not dens:
            continue
        any_slot = True
        out += ["**%s** — %d light, %d dark override%s%s" % (
            s, len(light), len(dark), "s" if len(dark) != 1 else "",
            (", %d densities" % len(dens)) if dens else "")]
        out += ["", "| slot | light | dark | cited |", "|---|---|---|---|"]
        prov = col.get("provenance") or {}
        for k, v in light.items():
            out.append("| `%s` | %s | %s | %s |" % (
                k, esc(v), esc(dark.get(k, "—")), "yes" if k in prov else "**no**"))
        out += [""]
    if not any_slot:
        out += ["_This component defines no slots — every cell is a literal._", ""]

    # then the full row × system grid
    out += ["### Rows", "",
            "| # | row | piece | policy | salt | shadcn | m3 |",
            "|---|---|---|---|---|---|---|"]
    cites = []
    for i, r in enumerate(tpl["rows"], 1):
        vals = []
        for s in SYSTEMS:
            col = cols[s]
            cell = (col.get("cells") or {}).get(r["id"]) if col else None
            v, c = render_cell(cell)
            vals.append(v)
            if c:
                cites.append((r["id"], s, c))
        out.append("| %d | `%s` | %s | %s | %s | %s | %s |" % (
            i, r["id"], r.get("piece", ""), r.get("policy", ""), *vals))
    out += [""]

    # citations, kept out of the grid so the grid stays readable
    if cites:
        out += ["<details><summary>Citations — %d cells carry a source or note</summary>" % len(cites),
                "", "| row | system | citation |", "|---|---|---|"]
        for rid, s, c in cites:
            out.append("| `%s` | %s | %s |" % (rid, s, esc(c)[:400]))
        out += ["", "</details>", ""]

    out += [END]
    return "\n".join(out)


def main():
    comps = sorted(f.replace(".template.json", "")
                   for f in os.listdir(TPL) if f.endswith(".template.json"))
    touched, missing = [], []
    for comp in comps:
        doc = os.path.join(DOCS, comp.upper() + "-MATRIX.md")
        if not os.path.exists(doc):
            missing.append(comp)
            continue
        text = open(doc, encoding="utf-8").read()
        block = block_for(comp)
        if BEGIN in text and END in text:
            text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block,
                          text, flags=re.S)
        else:
            text = text.rstrip() + "\n\n" + block + "\n"
        open(doc, "w", encoding="utf-8").write(text)
        touched.append(comp)

    print("synced values into %d matrix docs: %s" % (len(touched), ", ".join(touched)))
    if missing:
        print("NO MATRIX DOC (component built but undocumented): %s" % ", ".join(missing))
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
