#!/usr/bin/env python3
"""Theme compiler: themes/theme-*.json -> dist/theme-<name>.css

Consumption order: tokens/base.css (contract defaults + compat aliases)
then dist/theme-<name>.css (the theme's overrides). Dark mode = .dark
class; density (when the theme declares it) = [data-density="..."].
Generated files carry a DO NOT EDIT header; hand-editing dist is a
conformance violation.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTE_KEYS = {"source", "strategy", "darkModeNote", "cursorNote", "rule", "note"}
# adapter key -> contract var name (identity unless mapped)
CHAR_MAP = {"ui-case": "action-case", "ui-tracking": "action-tracking",
            "radius": "radius-knob"}


def clean(value):
    """Return a CSS-usable value or None (prose/annotated values are skipped)."""
    if not isinstance(value, str):
        return str(value) if isinstance(value, (int, float)) else None
    v = value.split("—")[0].split(" (")[0].strip()
    return v or None


def emit(pairs):
    return "".join(f"  --{k}: {v};\n" for k, v in pairs if v is not None)


def color_pairs(tokens, mode):
    pairs = [(k, clean(v)) for k, v in tokens.get(mode, {}).items()]
    for tone, parts in tokens.get("status", {}).items():
        pairs.append((f"status-{tone}", clean(parts.get("base"))))
        pairs.append((f"status-{tone}-surface", clean(parts.get("surface"))))
        pairs.append((f"status-{tone}-border", clean(parts.get("border"))))
        pairs.append((f"on-status-{tone}", clean(parts.get("on"))))
    for section, body in tokens.items():
        if not section.startswith("growth-"):
            continue
        for k, v in body.items():
            if k in NOTE_KEYS:
                continue
            if isinstance(v, dict):
                if mode in v:
                    pairs.append((k, clean(v[mode])))
            elif mode == "light":  # mode-independent growth values once
                pairs.append((k, clean(v)))
    return pairs


def character_pairs(tokens):
    pairs = []
    for section in ("shape", "type", "focus", "icons"):
        for k, v in tokens.get(section, {}).items():
            if k in NOTE_KEYS or k == "default-set":
                continue
            name = CHAR_MAP.get(k, k)
            pairs.append((name, clean(v)))
            if k == "radius":  # keep compat --radius in sync with the knob
                pairs.append(("radius", clean(v)))
    rhythm = tokens.get("rhythm", {})
    if "byDensity" not in rhythm:
        pairs += [(CHAR_MAP.get(k, k), clean(v)) for k, v in rhythm.items()]
    for k, v in tokens.get("motion", {}).get("duration", {}).items():
        pairs.append((f"duration-{k}", clean(v)))
    for k, v in tokens.get("motion", {}).get("easing", {}).items():
        pairs.append((f"easing-{k}", clean(v)))
    for k, v in tokens.get("layers", {}).items():
        if k not in NOTE_KEYS:
            pairs.append((f"layer-{k}", clean(v)))
    for k, v in tokens.get("elevation", {}).items():
        if k not in NOTE_KEYS:
            pairs.append((f"elevation-{k}", clean(v)))
    action = tokens.get("typeRoles", {}).get("action", {})
    if isinstance(action, dict):
        pairs.append(("action-case", clean(action.get("case"))))
        pairs.append(("action-tracking", clean(action.get("tracking"))))
        pairs.append(("ui-weight", clean(action.get("weight"))))
    for k, v in tokens.get("growth-1.2.0", {}).items():
        if k in NOTE_KEYS or isinstance(v, dict):
            continue
        pairs.append((k, clean(v)))
    size = tokens.get("growth-1.2.0", {}).get("size-overlay", {})
    if isinstance(size, dict):
        for s in ("sm", "md", "lg"):
            if s in size:
                pairs.append((f"size-overlay-{s}", clean(size[s])))
    return pairs


def build(path):
    theme = json.loads(path.read_text())
    tokens = theme["tokens"]
    name = theme["name"]
    out = [f"/* GENERATED by scripts/build-themes.py from {path.name} — DO NOT EDIT.\n"
           f"   Import after tokens/base.css. Theme: {theme.get('title', name)}. */\n"]
    out.append(":root {\n" + emit(color_pairs(tokens, "light"))
               + emit(character_pairs(tokens)) + "}\n")
    out.append(".dark {\n" + emit(color_pairs(tokens, "dark")) + "}\n")
    by_density = tokens.get("rhythm", {}).get("byDensity")
    if by_density:
        default = theme["capabilities"]["density"]["default"]
        out.append(f'/* density (default: {default}) */\n')
        out.append(":root {\n" + emit([(k, clean(v)) for k, v in by_density[default].items()]) + "}\n")
        for density, values in by_density.items():
            out.append(f'[data-density="{density}"] {{\n'
                       + emit([(k, clean(v)) for k, v in values.items()]) + "}\n")
    dist = ROOT / "dist"
    dist.mkdir(exist_ok=True)
    target = dist / f"theme-{name}.css"
    target.write_text("\n".join(out))
    return target


if __name__ == "__main__":
    built = [build(p) for p in sorted((ROOT / "themes").glob("theme-*.json"))]
    for t in built:
        print(f"built {t.relative_to(ROOT)} ({t.stat().st_size} bytes)")
    sys.exit(0)
