// GENERATED imports — every component in the registry, live.
import * as React from 'react'
import { Accordion, AccordionItem, AccordionPanel, AccordionTrigger } from '../registry/accordion/accordion'
import { Alert } from '../registry/alert/alert'
import { AlertDialog } from '../registry/alert-dialog/alert-dialog'
import { AspectRatio } from '../registry/aspect-ratio/aspect-ratio'
import { Avatar, AvatarGroup } from '../registry/avatar/avatar'
import { Badge } from '../registry/badge/badge'
import { Breadcrumb, BreadcrumbCurrent, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbOverflow, BreadcrumbSeparator } from '../registry/breadcrumb/breadcrumb'
import { Button } from '../registry/button/button'
import { ButtonGroup, ButtonGroupSeparator, ButtonGroupText } from '../registry/button-group/button-group'
import { Calendar } from '../registry/calendar/calendar'
import { Card, CardAction, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '../registry/card/card'
import { Carousel } from '../registry/carousel/carousel'
import { Chart } from '../registry/chart/chart'
import { Checkbox } from '../registry/checkbox/checkbox'
import { Collapsible, CollapsiblePanel, CollapsibleTrigger } from '../registry/collapsible/collapsible'
import { Command } from '../registry/command/command'
import { ContextMenu, ContextMenuGroupLabel, ContextMenuItem, ContextMenuSeparator } from '../registry/context-menu/context-menu'
import { Dialog } from '../registry/dialog/dialog'
import { Drawer } from '../registry/drawer/drawer'
import { DropdownMenu } from '../registry/dropdown-menu/dropdown-menu'
import { Empty } from '../registry/empty/empty'
import { Field } from '../registry/field/field'
import { Form, FormControl, FormDescription, FormItem, FormLabel, FormMessage } from '../registry/form/form'
import { HoverCard } from '../registry/hover-card/hover-card'
import { Icon } from '../registry/icon/icon'
import { Input } from '../registry/input/input'
import { InputGroup, InputGroupAddon, InputGroupControl } from '../registry/input-group/input-group'
import { InputOTP } from '../registry/input-otp/input-otp'
import { Item, ItemGroup, ItemSeparator } from '../registry/item/item'
import { Kbd } from '../registry/kbd/kbd'
import { Label } from '../registry/label/label'
import { Menubar } from '../registry/menubar/menubar'
import { NativeSelect, NativeSelectGroup, NativeSelectOption } from '../registry/native-select/native-select'
import { NavigationMenu } from '../registry/navigation-menu/navigation-menu'
import { Pagination, PaginationCountLabel, PaginationEllipsis, PaginationItem, PaginationList, PaginationNext, PaginationPage, PaginationPrevious } from '../registry/pagination/pagination'
import { Popover } from '../registry/popover/popover'
import { Progress } from '../registry/progress/progress'
import { RadioGroup, RadioGroupItem } from '../registry/radio-group/radio-group'
import { Resizable, ResizableHandle, ResizablePanel } from '../registry/resizable/resizable'
import { ScrollArea } from '../registry/scroll-area/scroll-area'
import { Select } from '../registry/select/select'
import { Separator } from '../registry/separator/separator'
import { Sheet } from '../registry/sheet/sheet'
import { Sidebar } from '../registry/sidebar/sidebar'
import { Skeleton } from '../registry/skeleton/skeleton'
import { Slider } from '../registry/slider/slider'
import { Toaster } from '../registry/sonner/sonner'
import { Spinner } from '../registry/spinner/spinner'
import { Switch } from '../registry/switch/switch'
import { Table, TableBody, TableCaption, TableCell, TableHead, TableHeader, TableRow } from '../registry/table/table'
import { Tabs, TabsList, TabsPanel, TabsTrigger } from '../registry/tabs/tabs'
import { Textarea } from '../registry/textarea/textarea'
import { Toggle } from '../registry/toggle/toggle'
import { ToggleGroup, ToggleGroupItem } from '../registry/toggle-group/toggle-group'
import { Tooltip } from '../registry/tooltip/tooltip'
